output0: countpageFault.c countpageFault1.c countpageFault2.c countpageFault3.c countpageFault4.c countpageFault5.c countpageFault6.c countpageFault7.c countpageFault8.c countpageFault9.c output1 output2 output3 output4 output5 output6 output7 output8 output9 plot0 plot0.c plot1 plot1.c runall runall.c
	gcc countpageFault.c -o output0
	
output1: countpageFault1.c
	gcc countpageFault1.c -o output1
	
output2: countpageFault2.c
	gcc countpageFault2.c -o output2
	
output3: countpageFault3.c
	gcc countpageFault3.c -o output3
	
output4: countpageFault4.c
	gcc countpageFault4.c -o output4
	
output5: countpageFault5.c
	gcc countpageFault5.c -o output5
	
output6: countpageFault6.c
	gcc countpageFault6.c -o output6

output7: countpageFault7.c
	gcc countpageFault7.c -o output7
	
output8: countpageFault8.c
	gcc countpageFault8.c -o output8
	
output9: countpageFault9.c
	gcc countpageFault9.c -o output9
	
plot0: plot0.c
	gcc plot0.c -o plot0
	
plot1: plot1.c
	gcc plot1.c -o plot1

runall: runall.c
	gcc runall.c -o runall
